In [43]:
from db_settings import get_engine
import pandas as pd

In [44]:
engine = get_engine()
prices = pd.read_sql(
    """
    select * from raw_prices
    """,
    engine
)

In [45]:
prices['date'] = pd.to_datetime(prices['date']).dt.normalize()
prices.dtypes

date            datetime64[ns]
country                 object
devise                  object
gold_24k               float64
gold_22k               float64
gold_18k               float64
gold_14k               float64
gold_10k               float64
silver_price           float64
dtype: object

In [46]:
geo_po = pd.read_sql(
    """
    select * from geopo_data
    """,
    engine
)

In [47]:
geo_po['date'] = pd.to_datetime(geo_po['date']).dt.normalize()
geo_po = geo_po[geo_po['date'] >= '2016-01-01']
geo_po.dtypes

date                  datetime64[ns]
country                       object
total_events                   int64
political_events               int64
war_intensity                float64
crisis_index                 float64
political_pressure           float64
dtype: object

In [48]:
geo_po.tail()

,date,country,total_events,political_events,war_intensity,crisis_index,political_pressure
1829027,2026-05-24,WST,62,12,0.016129,2.303226,0.193548
1829028,2026-05-24,YEM,25,3,0.000000,2.864000,0.120000
1829029,2026-05-24,ZAF,149,57,0.046980,-0.715436,0.382550
1829030,2026-05-24,ZMB,14,3,0.214286,-0.742857,0.214286
1829031,2026-05-24,ZWE,63,20,0.095238,0.122222,0.317460

In [49]:
macro_data = pd.read_sql(
    """
    select * from macro_data
    """,
    engine
)

In [50]:
macro_data['date'] = pd.to_datetime(macro_data['date']).dt.normalize()
macro_data = macro_data[macro_data['date'] >= '2016-01-01']
macro_data.tail(10)

           date  fed_rate  real_rate  CPI  GDP       DXY  Unemployment
6088 2026-05-04       NaN        NaN  NaN  NaN  118.8264           NaN
6089 2026-05-05       NaN        NaN  NaN  NaN  118.6207           NaN
6090 2026-05-06       NaN        NaN  NaN  NaN  118.0982           NaN
6091 2026-05-07       NaN        NaN  NaN  NaN  118.0116           NaN
6092 2026-05-08       NaN        NaN  NaN  NaN  118.0392           NaN
6093 2026-05-11       NaN        NaN  NaN  NaN  118.0562           NaN
6094 2026-05-12       NaN        NaN  NaN  NaN  118.5238           NaN
6095 2026-05-13       NaN        NaN  NaN  NaN  118.4737           NaN
6096 2026-05-14       NaN        NaN  NaN  NaN  118.6696           NaN
6097 2026-05-15       NaN        NaN  NaN  NaN  119.2825           NaN

In [51]:
gold_reserv = pd.read_sql(
    """
    select * from reserves_gold
    """,
    engine
)

In [ ]:
gold_reserv = gold_reserv[gold_reserv["year"] >= 2016]
gold_reserv["date"] = pd.to_datetime(gold_reserv["year"].astype(str) + "-01-01")

In [57]:
gold_reserv.head(10)
print(gold_reserv.dtypes)

country_name    object
country_code    object
year             int64
value            int64
dtype: object

In [ ]:
vix_oil = pd.read_sql(
    """
    select * from vix_oil_data
    """,
    engine
)

In [ ]:
vix_oil['date'] = pd.to_datetime(geo_po['date']).dt.normalize()
print(vix_oil.dtypes)
vix_oil.tail()

Date    datetime64[ns]
vix            float64
oil            float64
date    datetime64[ns]
dtype: object

           Date        vix         oil date
2610 2026-05-19  18.059999  107.769997  NaT
2611 2026-05-20  17.440001   98.260002  NaT
2612 2026-05-21  16.760000   96.349998  NaT
2613 2026-05-22  16.700001   96.599998  NaT
2614 2026-05-25  16.690001   96.599998  NaT