In [19]:
from db_settings import get_engine
import pandas as pd

In [21]:
engine = get_engine()
prices_df = pd.read_sql( """ select * from public.raw_prices """ , engine,)
geopo_df = pd.read_sql( """ select * from public.geopo_data """ , engine,)
macro_df = pd.read_sql( """ select * from public.macro_data """ , engine,)
vix_oil_df = pd.read_sql( """ select * from public.vix_oil_data """ , engine,)

In [28]:
prices_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29376 entries, 0 to 29375
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          29376 non-null  datetime64[ns]
 1   country       29376 non-null  object
 2   devise        29376 non-null  object
 3   gold_24k      29376 non-null  float64
 4   gold_22k      29376 non-null  float64
 5   gold_18k      29376 non-null  float64
 6   gold_14k      29376 non-null  float64
 7   gold_10k      29376 non-null  float64
 8   silver_price  29376 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(2)
memory usage: 2.0+ MB

In [23]:
prices_df.isna().sum()

date            0
country         0
devise          0
gold_24k        0
gold_22k        0
gold_18k        0
gold_14k        0
gold_10k        0
silver_price    0
dtype: int64

In [29]:
prices_df["date"] = pd.to_datetime(prices_df["date"])
prices_df = prices_df.sort_values("date")

In [31]:
freq = pd.infer_freq(prices_df["date"])
print("Fréquence détectée :", freq)

Fréquence détectée : None

In [26]:
geopo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1829032 entries, 0 to 1829031
Data columns (total 7 columns):
 #   Column              Dtype
---  ------              -----
 0   date                object
 1   country             object
 2   total_events        int64
 3   political_events    int64
 4   war_intensity       float64
 5   crisis_index        float64
 6   political_pressure  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 97.7+ MB

In [43]:
geopo_df["date"] = pd.to_datetime(geopo_df["date"])
geopo_df = geopo_df.sort_values("date")
geopo_df = geopo_df[geopo_df["date"] >= "2016-01-01"]
geopo_df = geopo_df[geopo_df["country"] == "USA"]
geopo_df = geopo_df.drop(columns = ["country"])

In [45]:
geopo_df.isna().sum()

date                  0
total_events          0
political_events      0
war_intensity         0
crisis_index          0
political_pressure    0
dtype: int64

In [47]:
macro_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6098 entries, 0 to 6097
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          6098 non-null   datetime64[ns]
 1   fed_rate      862 non-null    float64
 2   real_rate     533 non-null    float64
 3   CPI           951 non-null    float64
 4   GDP           317 non-null    float64
 5   DXY           5107 non-null   float64
 6   Unemployment  939 non-null    float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 333.6 KB

In [49]:
macro_df = macro_df[macro_df["date"] >= "2016-01-01"]

In [50]:
macro_df.head()

,date,fed_rate,real_rate,CPI,GDP,DXY,Unemployment
3357,2016-01-01,0.34,0.734506,237.652,18525.933,NaN,4.8
3358,2016-01-04,NaN,NaN,NaN,NaN,114.1595,NaN
3359,2016-01-05,NaN,NaN,NaN,NaN,114.2649,NaN
3360,2016-01-06,NaN,NaN,NaN,NaN,114.6177,NaN
3361,2016-01-07,NaN,NaN,NaN,NaN,114.6516,NaN

In [59]:
macro_df.isna().sum()

date               0
fed_rate        2617
real_rate       2616
CPI             2618
GDP             2700
DXY              155
Unemployment    2618
dtype: int64

In [60]:
macro_df.ffill()

,date,fed_rate,real_rate,CPI,GDP,DXY,Unemployment
3357,2016-01-01,0.34,0.734506,237.652,18525.933,NaN,4.8
3358,2016-01-04,0.34,0.734506,237.652,18525.933,114.1595,4.8
3359,2016-01-05,0.34,0.734506,237.652,18525.933,114.2649,4.8
3360,2016-01-06,0.34,0.734506,237.652,18525.933,114.6177,4.8
3361,2016-01-07,0.34,0.734506,237.652,18525.933,114.6516,4.8
...,...,...,...,...,...,...,...
6093,2026-05-11,3.64,1.634051,332.407,31856.257,118.0562,4.3
6094,2026-05-12,3.64,1.634051,332.407,31856.257,118.5238,4.3
6095,2026-05-13,3.64,1.634051,332.407,31856.257,118.4737,4.3
6096,2026-05-14,3.64,1.634051,332.407,31856.257,118.6696,4.3
6097,2026-05-15,3.64,1.634051,332.407,31856.257,119.2825,4.3

In [61]:
vix_oil_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2615 entries, 0 to 2614
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2615 non-null   datetime64[ns]
 1   vix     2613 non-null   float64
 2   oil     2613 non-null   float64
dtypes: datetime64[ns](1), float64(2)
memory usage: 61.4 KB

In [62]:
vix_oil_df.head()

        Date        vix        oil
0 2016-01-04  20.700001  36.759998
1 2016-01-05  19.340000  35.970001
2 2016-01-06  20.590000  33.970001
3 2016-01-07  24.990000  33.270000
4 2016-01-08  27.010000  33.160000

In [63]:
vix_oil_df.isna().sum()

Date    0
vix     2
oil     2
dtype: int64